from .util import ansi

CLUSTERS_CONFIG_TEMPLATE = """
#This is an autogenerated template, use the following entries as sample.
#[Cluster Name]
#configfile=[place here the path to your kubeconfig file]
"""

KUBEMGR_DEFAUL_CONFIG_TEMPLATE = """
[general]
editor=/usr/bin/vim
# Ucomment to use a custom viewer, by default uses internal viewer.
#viewer=/usr/bin/view
[tabs]
# Fixed tab, allows basic customizing
# Uses basic python formatting with some exceptions.
# MAX is replaced by the available width.
podstab.format=item.metadata.name:MAX,item.status.phase:>10

# Custom tabs
tab1.title=Cronjobs
tab1.kind=CronJob
tab1.group_version=batch/v1beta1

tab2.title=Jobs
tab2.kind=Job
tab2.group_version=batch/v1

tab3.title=Services
tab3.kind=Service
tab3.group_version=api/v1

tab4.title=Deployments
tab4.kind=Deployment
tab4.group_version=apps/v1

tab5.title=DaemonSets
tab5.kind=DaemonSet
tab5.group_version=apps/v1

tab6.title=ConfigMaps
tab6.kind=ConfigMap
tab6.group_version=api/v1

tab7.title=Secrets
tab7.kind=Secret
tab7.group_version=api/v1
"""
HELP_CONTENTS = f"""
{ansi.BOLD}Help:{ansi.RESET}
{ansi.BOLD}====={ansi.RESET}

{ansi.UNDERLINE}Keys:{ansi.RESET}
    h                : Show this help.
    tab              : cycles focus across UI components.
    esc              : Closes popup if open, otherwise 
                       closes the application.
    cursor up/down   : move across items in different lists.
    cursor left/right: switch across pods/cronjobs/jobs/etc. 
                       in main view when focused.
    for nodes, namespaces, pods, cronjobs, etc:
        v: display resource as Yaml
        e: Opens editor to edit resource.
        d: Deletes de selected resource
    for pods:
        l: View pod logs.
    for nodes:
        l: view labels for node.
    for namespaces:
        enter: toggle namespace filter, all other views will 
               filter its item by selected namespace

{ansi.UNDERLINE}Configuration files:{ansi.RESET}

    {ansi.BOLD}$HOME/.kubemgr/kubemgr.ini:{ansi.RESET} 
        General configuration file.
        editor=Absolute path to editor used for Yaml

    {ansi.BOLD}$HOME/.kubemgr/clusters.ini:{ansi.RESET} 
        Clusters configuration file.
        [Cluster name enclosed in brackets]
        configfile=[Absolute path to kubeconfig yaml file]

    {ansi.BOLD}$HOME/.kubemgr/colors.ini:{ansi.RESET}
        UI colors and styles.
"""
